const dupEntries = (base: any) => {
  const obj: any = {}

  for (const key in base) {
    const value = base[key]

    obj[key] = value
    obj[value] = key
  }

  return obj
}

export const Tags = dupEntries({
  p: 'P',
  head: 'HEAD',
  title: 'TITLE',
  body: 'BODY',
  h1: 'H1',
  h2: 'H2',
  h3: 'H3',
  h4: 'H4',
  h5: 'H5',
  h6: 'H6',
  span: 'SPAN',
  div: 'DIV',
  b: 'B',
  a: 'A',
  abbr: 'ABBR',
  address: 'ADDRESS',
  area: 'AREA',
  article: 'ARTICLE',
  aside: 'ASIDE',
  audio: 'AUDIO',
  base: 'BASE',
  bdi: 'BDI',
  bdo: 'BDO',
  blockquote: 'BLOCKQUOTE',
  br: 'BR',
  button: 'BUTTON',
  canvas: 'CANVAS',
  caption: 'CAPTION',
  cite: 'CITE',
  code: 'CODE',
  col: 'COL',
  colgroup: 'COLGROUP',
  data: 'DATA',
  datalist: 'DATALIST',
  dd: 'DD',
  del: 'DEL',
  details: 'DETAILS',
  dfn: 'DFN',
  dialog: 'DIALOG',
  dl: 'DL',
  dt: 'DT',
  em: 'EM',
  embed: 'EMBED',
  figure: 'FIGURE',
  footer: 'FOOTER',
  form: 'FORM',
  header: 'HEADER',
  hr: 'HR',
  i: 'I',
  iframe: 'IFRAME',
  img: 'IMG',
  input: 'INPUT',
  ins: 'INS',
  kbd: 'KBD',
  label: 'LABEL',
  legend: 'LEGEND',
  li: 'LI',
  link: 'LINK',
  main: 'MAIN',
  map: 'MAP',
  mark: 'MARK',
  meta: 'META',
  meter: 'METER',
  nav: 'NAV',
  style: 'STYLE',
})
